language: generic
sudo : retuired
services:
    - docker

before_install:
    - docker build -t sandeepsbais/react-test -f ./client/Dockerfile.dev ./client

#run test
script:
    - docker run -e CI=true sandeepsbais/react-test npm test

#build PROD images
after_success:
    - docker build -t sandeepsbais/multi-react-client ./client
    - docker build -t sandeepsbais/multi-server ./server
    - docker build -t sandeepsbais/multi-nginx ./nginx
    - docker build -t sandeepsbais/multi-worker ./worker
#docker hub login with CLI
    - echo "$DOCK_PASS" | docker login -u "$DOCK_ID" --password-stdin docker.io
#push images to docker hub
    - docker push sandeepsbais/multi-react-client
    - docker push sandeepsbais/multi-server
    - docker push sandeepsbais/multi-nginx
    - docker push sandeepsbais/multi-worker


